from harvesters.core import Harvester

with Harvester() as h:
    # h.add_cti_file('/opt/cvb-13.03.003/drivers/genicam/libGevTL.cti')
    h.add_cti_file('/opt/mvIMPACT_Acquire/lib/x86_64/mvGenTLProducer.cti')
    h.update_device_info_list()
    with h.create_image_acquirer(0) as ia:
        a = dir(ia.remote_device.node_map)
        for i in a:
            print(i)

# GenICam Nodes

# ALCAreaEnable
# ALCAreaEnableAll
# ALCAreaSelector
# ALCControlSpeed
# ALCReference
# AWBAreaEnable
# AWBAreaSelector
# AWBControlSpeed
# AcquisitionControl
# AcquisitionFrameCount
# AcquisitionFrameRate
# AcquisitionFrameRateRaw
# AcquisitionMode
# AcquisitionStart
# AcquisitionStop
# ActionControl
# ActionDeviceKey
# ActionGroupKey
# ActionGroupMask
# ActionSelector
# AnalogBaseGain
# AnalogBaseGainSelector
# AnalogControl
# AutoGainControlGainRawMax
# AutoGainControlGainRawMin
# AutoShutterControlExposureMax
# AutoShutterControlExposureMin
# BalanceWhiteAuto
# BlackLevel
# BlackLevelSelector
# BlemishDetect
# BlemishDetectPositionIndex
# BlemishDetectPositionX
# BlemishDetectPositionY
# BlemishDetectThreshold
# BlemishEnable
# BlemishNum
# ClockPreScaler
# CommandSequenceIndex
# CurrentSequenceIndex
# DarkCompression
# DeviceControl
# DeviceFirmwareVersion
# DeviceID
# DeviceManufacturerInfo
# DeviceModelName
# DeviceReset
# DeviceTemperature
# DeviceUserID
# DeviceVendorName
# DeviceVersion
# DigitalIOControl
# EventAcquisitionTrigger
# EventAcquisitionTriggerData
# EventAcquisitionTriggerFrameID
# EventAcquisitionTriggerTimestamp
# EventControl
# EventExposureEnd
# EventExposureEndData
# EventExposureEndFrameID
# EventExposureEndTimestamp
# EventExposureStart
# EventExposureStartData
# EventExposureStartFrameID
# EventExposureStartTimestamp
# EventFrameEnd
# EventFrameEndData
# EventFrameEndFrameID
# EventFrameEndTimestamp
# EventFrameStart
# EventFrameStartData
# EventFrameStartFrameID
# EventFrameStartTimestamp
# EventJaiFVALEnd
# EventJaiFVALEndData
# EventJaiFVALEndFrameID
# EventJaiFVALEndTimestamp
# EventJaiFVALStart
# EventJaiFVALStartData
# EventJaiFVALStartFrameID
# EventJaiFVALStartTimestamp
# EventLine2FallingEdge
# EventLine2FallingEdgeData
# EventLine2FallingEdgeFrameID
# EventLine2FallingEdgeTimestamp
# EventLine2RisingEdge
# EventLine2RisingEdgeData
# EventLine2RisingEdgeFrameID
# EventLine2RisingEdgeTimestamp
# EventLine3FallingEdge
# EventLine3FallingEdgeData
# EventLine3FallingEdgeFrameID
# EventLine3FallingEdgeTimestamp
# EventLine3RisingEdge
# EventLine3RisingEdgeData
# EventLine3RisingEdgeFrameID
# EventLine3RisingEdgeTimestamp
# EventLine5FallingEdge
# EventLine5FallingEdgeData
# EventLine5FallingEdgeFrameID
# EventLine5FallingEdgeTimestamp
# EventLine5RisingEdge
# EventLine5RisingEdgeData
# EventLine5RisingEdgeFrameID
# EventLine5RisingEdgeTimestamp
# EventNotification
# EventSelector
# ExposureAuto
# ExposureMode
# ExposureTime
# ExposureTimeRaw
# FactoryBlackLevelRawAll
# FactoryBlackLevelRawAllforDC
# FactoryBlackLevelRawBlue
# FactoryBlackLevelRawBlueforDC
# FactoryBlackLevelRawRed
# FactoryBlackLevelRawRedforDC
# FactoryBlackOffsetAll
# FactoryBlackOffsetAllforDC
# FactoryBlemishBlackDataIndex
# FactoryBlemishBlackDataPositionX
# FactoryBlemishBlackDataPositionY
# FactoryBlemishBlackDetect
# FactoryBlemishBlackNum
# FactoryBlemishBlackThreshold
# FactoryBlemishWhiteDataIndex
# FactoryBlemishWhiteDataPositionX
# FactoryBlemishWhiteDataPositionY
# FactoryBlemishWhiteDetect
# FactoryBlemishWhiteNum
# FactoryBlemishWhiteThreshold
# FactoryBootAreaSet
# FactoryCCPFunctionMode
# FactoryDeviceFPGAVersion
# FactoryDeviceID
# FactoryDeviceVersion
# FactoryFineGainBlue
# FactoryFineGainRed
# FactoryGainAdjustAll
# FactoryGevMACAddressHigh
# FactoryGevMACAddressLow
# FactoryHighDynamicRangePoint
# FactoryInGain
# FactoryModelName
# FactoryPhaseAdjust
# FactoryTemperatureFactor
# Gain
# GainAuto
# GainRaw
# GainSelector
# Gamma
# GevCCP
# GevCurrentDefaultGateway
# GevCurrentIPAddress
# GevCurrentIPConfigurationDHCP
# GevCurrentIPConfigurationLLA
# GevCurrentIPConfigurationPersistentIP
# GevCurrentSubnetMask
# GevDeviceModeCharacterSet
# GevDeviceModeIsBigEndian
# GevFirstURL
# GevHeartbeatTimeout
# GevInterfaceSelector
# GevMACAddress
# GevMCDA
# GevMCPHostPort
# GevMCRC
# GevMCSP
# GevMCTT
# GevMessageChannelCount
# GevNumberOfInterfaces
# GevPersistentDefaultGateway
# GevPersistentIPAddress
# GevPersistentSubnetMask
# GevSCDA
# GevSCPD
# GevSCPHostPort
# GevSCPSDoNotFragment
# GevSCPSPacketSize
# GevSCSP
# GevSecondURL
# GevStreamChannelCount
# GevStreamChannelSelector
# GevSupportedIPConfigurationDHCP
# GevSupportedIPConfigurationLLA
# GevSupportedIPConfigurationPersistentIP
# GevSupportedOption
# GevSupportedOptionSelector
# GevSupportedOptionalCommandsConcatenation
# GevSupportedOptionalCommandsEVENT
# GevSupportedOptionalCommandsEVENTDATA
# GevSupportedOptionalCommandsPACKETRESEND
# GevSupportedOptionalCommandsWRITEMEM
# GevTimestampControlLatch
# GevTimestampControlReset
# GevTimestampTickFrequency
# GevTimestampValue
# GevVersionMajor
# GevVersionMinor
# Height
# HeightMax
# ImageFormatControl
# JAICustomControlALC
# JAICustomControlBlemish
# JAICustomControlFactory
# JAICustomControlMisc
# JAICustomControlMultiROI
# JAICustomControlSequenceROI
# JAICustomFactorySetSave
# JAILUTMode
# LUTControl
# LUTIndex
# LUTSelector
# LUTValue
# LineFormat
# LineInverter
# LineMode
# LineSelector
# LineSource
# LineStatus
# MultiRoiHeight
# MultiRoiIndex
# MultiRoiIndexMax
# MultiRoiOffsetX
# MultiRoiOffsetY
# MultiRoiWidth
# OffsetX
# OffsetY
# OptInFilterSelector
# PayloadSize
# PixelFormat
# PulseGeneratorClearActivation
# PulseGeneratorClearInverter
# PulseGeneratorClearSource
# PulseGeneratorClearSyncMode
# PulseGeneratorClock
# PulseGeneratorEndPoint
# PulseGeneratorEndPointMs
# PulseGeneratorFrequency
# PulseGeneratorLength
# PulseGeneratorLengthMs
# PulseGeneratorPulseWidthMs
# PulseGeneratorRepeatCount
# PulseGeneratorSelector
# PulseGeneratorStartPoint
# PulseGeneratorStartPointMs
# PulseGenerators
# Root
# SequenceLutMode
# SequenceRepetition
# SequenceReset
# SequenceRoiBlackLevel
# SequenceRoiExposureTime
# SequenceRoiFrameCount
# SequenceRoiGainAll
# SequenceRoiGainBlue
# SequenceRoiGainRed
# SequenceRoiHeight
# SequenceRoiIndex
# SequenceRoiLutEnable
# SequenceRoiNextIndex
# SequenceRoiOffsetX
# SequenceRoiOffsetY
# SequenceRoiWidth
# TestImageSelector
# TransportLayerControl
# TriggerActivation
# TriggerMode
# TriggerOption
# TriggerOverLap
# TriggerSelector
# TriggerSoftware
# TriggerSource
# UserOutputSelector
# UserOutputValue
# UserSetControl
# UserSetLoad
# UserSetSave
# UserSetSelector
# VideoSendModeSelector
# Width
# WidthMax
# __class__
# __del__
# __delattr__
# __dict__
# __dir__
# __doc__
# __enter__
# __eq__
# __exit__
# __format__
# __ge__
# __getattr__
# __getattribute__
# __gt__
# __hash__
# __init__
# __init_subclass__
# __le__
# __lt__
# __module__
# __ne__
# __new__
# __reduce__
# __reduce_ex__
# __repr__
# __setattr__
# __sizeof__
# __str__
# __subclasshook__
# __swig_destroy__
# __swig_getmethods__
# __swig_setmethods__
# __weakref__
# _concrete_port
# _connect
# _destroy
# _get_device_info
# _get_device_name
# _get_node
# _get_nodes
# _invalidate_nodes
# clear_xml_cache
# connect
# device_info
# disconnect
# get_node
# has_node
# load_xml_from_file
# load_xml_from_string
# load_xml_from_zip_file
# nodes
# pointer
# poll
# this